
jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd server-family-expense-tracker
    after_success:
      - npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "HuxlG0thTeSqQbMdoqS9jo/9buPCo9bJ7sl3tK0jvLk2rRjbzW8QNsGeUV1QcTS0Mren32VsT89sDIwmx2hpnzhel8u0J8mnIpe3h87c9TcwfRDRO4qEoqhCZHP/QqVcq00v9H3AwI50hIsbh1RgcjBccXSjfc5y+BsiV/ocVk93LP257SmUyvSd1piqgI2J4Hsensbol5WqWZ3Jh1sh/NgnnmxT7x15Ud+GVGJP2eaPLxNXqRv8soWFDMrDgHF20CxbGlAq5UuQNGym0vX3pgbC4W6QmpFGN1U0N7Cw0ASxotaFjpfBJ04K7jDMn6kKr9KMuERfRBPsceK3SuSAbT+XavXyCYBdVzu1Wz4CKYqfuQK8pRn9pHF2dXbaEeQ2Mj3/13q9fBg0CbXqBDp/w9K4nL7HIRYO57y0ki1mZpeCSt/JXcjHzQ/YYOwgp2+jTZbyoKVW0UCqo8SJ4zWktXrZ6Dr3D0R4tT2+Z25M4WbXC7VX5eHZyL3Wt94956vEMyp9PFUoUvW1gPpJEd0FnvygAHIgeCn4t7LCqpuz9r/xURp44BU7hpSkctrYaJuFfEu7B9w5DAUtVVGrkFJsFvkUFGozZgI72nVYB8WOPiRye788NbhQHcVS5IAaRx7nFiutfKcQrUDT1KbcHqcVtY/9KnezTxSoaJlyTvJ4wos="
      app: family-expense-tracker
      on: main