
jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd server-family-expense-tracker
    after_success:
      - npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "SRQippl46FwL0ZGE90jPefZQreGwsbued0LMaiGbo4Chi9bXyX7llj664yOoAxPmb4tGKiaNROBjR/DwRIVmObkdpu5C+ySG6dRth1aPpn78gDFCE/ui0/M/wV2pOtaxwe6Qbxn7hdGUqaMhNnLkCDavvmZVUErnv8zoeJGoXWoO5EkbwzWlHlvu8I3flakXNsbq4VqFG2HJmFoxJcW7p0lEaAZ4ShFPoo/zIRvVLJy0rHNoY84A6uAuvrlhuM5cGdz5vyaSrPOhzW+y2BL3Bw4GoqrAZLILpfnBvPJ4exHY6P1DOeVEUZ6InADZRS6aBRgSmjlGsZ88E6I7RuH1GBAqxXShCAeK4r/CrlZX/5U4ybBhE5SHZNoLfiQmhRU9nZh0dM0X+AWlaMQoFVVHyl/LmYnUSorI87XhWt3U0TRI5lWwUvCO5/tRNPjhvoB47w80HrVWGO1BpsxGuLC4u9KQPpauybbCQvurOW9Lj/n2TjWmrMb4oenr009CutQKAa/65WeKcQTxVMwp0P7yce9VUkmpHAEnDqLCRUOMyE3KZxoqRGDrcp0PTicv4LBGHBxgi6umuKt16xn2XBNNR9iWKlPk7pdkLkreUqh/i7zgQ83f4QjRG0i4h1B5/UJEszRsrU/Pg9SZ067sApuQFzVSyU6r6/BUT1ZMV3ywKtQ="
      app: family-expense-tracker
      on: main