jobs:
  include:

  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "K9klbdtQ4x17seo/NtyHuGbdQrdQuUoncq3S9DHTxs0huEKyWqOm7nOC3PIMc6HyQ+9RhpiG1W/qle/YOJb78Ch7Hd5yv/I1hJcneGTqHJQzt1lJylOdhoKU15yMRjTvJlZbX2y0IuECCDVy1Z1GTIosyw3oz2BcJOG3k9L+GVPtQ7YcxyxzkmLR/NS2Nk+nS4oWGmliVX7/92o/5agWosKxZkdHqPo3l6EdFgtZR5mfCzmETRNkfr0jHrNIs9NBBA4XBoefcAbhwZ9DQ8VhGFoCIWpZYJx1JJ0rckZnS+CW2fQPfkZZU0RKhWJctNGNdX/PffI1AMvcHYrWTlq+vP364b0HHnKHG0KzVm7VczIsZVhDawMP35emMG2V4k7waNrEls1zu3WECRU9ZSu/X/fghve81f8sv9d9SfuspWm5DehQ00FzCQMAik8CzA2EbaZWRW3I2lG6Txhfzw3I5A0EHZt11TrZwqF1XnK5Y5RBCnwByA+gm5VBMWSYVFTnEfnYr6kEp85Hi7qyrtL+04zdB1c/7Ajs+2yxcI3wna8uGQsRMRahoeSUNvwhS9/oxAIZ7AWN3WeVuVoYJ2KlG/agJ6YtmAdE6HP1mDVobbm8CdrEVHblkW9YjCVSnrVI552znH/DEwKP7u0NATf7WcVTMyICpJYY0kDqr36yVXE="
      app: family-expense-tracker
      on: main