
jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd server-family-expense-tracker
    after_success:
      - npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "k0c1jAl8k6bGcCdLgwywE3xIKUr5dqfcpxa4D/TRlkKijJp18MKoazh6KAyleH5429qwIP+W9oR1AtfZwUUICfAzRxMMW9d2s4eTt5ISOOmJtki18EEYuvmBzZwuJcHikk5dDqR/FieV0SGME8ZALHw4DoY8Ykqmb/AZtH9SBFTcVYo/1MyYtRaQFOOf/o0YIAMwrTWVOsBQwIg82JZASqV2VePGa5xu95GHnpauLW6Z5duCamPraHi+QI724qNrea+u6O7AT1jofwhLkxVhH7pKZ+s+5iaEnJ14mfx/A6YGG8wnkgOScGkOEZvuG7HdxsV6cKlhTg4Lf/DfJC6i0GNLl+Z7UEEixI3mia5x7OBI37w0dqQ+aNKzAFv4cWZC4bwFfTDDkvOcWC7xpooMqYc0af+EP0sP3bG2maDF3iCgpGKBNwIj8imCo5LIct2TxmadoB/fPYNYuC5JOMKb191CjJY4ya27q3V2+dDkPc327mO5KOzhPRiqux3uzYw4QfYbf3cAB6Q/TQRWiG8bihMyUWFI0RSGxWLJlVcBjNJTgALL/nws0H17to1n9aYYJPE85V6Zv0C3NKtK8cNvzPaVkAA7ajwIzerG9qvyCRnqNs4H8Azl/jKDsBvZboHiTyp6eWD7CLK8kbbZBTJXI0VPbk+wiAin7GlY8Xo3jbs="
      app: family-expense-tracker
      on: main