
jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd server-family-expense-tracker
    after_success:
      - npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "VW7BNGyQ8aQQcPRURI7vWFjf45blUrfxdssh2ZcD6yqA+/AcSry2nA34dvD5tWzpJ0F1LilF72qna7ZdmRF74tEsMnXXJeNxN6rxC3VWyO6LtUaKXmLvrmfepqer1JrWh/8XqQlhvbmZ22PrTHYZe6ykpSMF4PwbVo5CKan3bBlHjXeGbjHmYfc7EPm9+1+/MB4O2o3ohMWiaiLkR5q6pkX/HrqilFZ8ZWx8P9/kMjNCpuDDR0Fbje8TmvFi6KUvwkkqrfT2GhsSgFGIvu1qXoxt1gP4rZ3TldTdXalfVb0MxPyLjMs37JnQRPWI6CGjMYpVp8H6mtFap/IZD/0DW71Ut15wZzKS0Wpgj8oASYeBIQf4hZIBWBrLw3u1ZfyMOt6EoUoJr/mxdtJT7Ru5VP/wx14JgJ04Z+RjehSG/ejfWSPkSFI0NQrOg8mqHDKAz402F14STqEDcfKCo9Uv37Gd3sLGF/Dlv54ZYq3+ZNYxOyC7eOoIp3qqfZhkgV/P5/7R1IgOEhvmL+YQfOgpplMBiQnYWPbU+6F/BztbKzSyGU4WeIMc4bFDd0cVfvJrRLvVGCkz7qEkR5Y/QEfmi1VMfNDKFG8vhSIj40iWrKIJt2tihiMcLReMu8Tr8yhWG7MH4u+zefM1tROflwXI/6lfuyyyabnQGN4b6O72Mmo="
      app: family-expense-tracker
      on: main