jobs:
  include:

  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "B+udTeR5Hr65xDHLmDUTfm79Ze389SeoFFsk4mSAJyVIIF+tj4pNPD4by/cDMtYJM23M2TSj5rSx6ikgn+rpTDDnPi65+ywyNUsFcoZTbfy60B1YG1m94MtiKWIT6J1xHOcoO6fnxl1GXHYB6WOk++kHXddMp5tC0p7F5gFagVYOynNVMKBpT/W73EvjbeMIPxHhAXTW/SLjiwh62OU1Xf0wTc4K8swwgNSw1yaPUJbfz+laxXjcyXRamlwP5ne5aZL1rG/qXD/Pg3QGYy2yjYqACdXRjmxOtL7OvP7/s73c7F86ehOZ/ppSix+D/Y/KqLeZFwUGMVwbnoIYYki5O1CbA+X3ai8O7CvditJJFwd7HB3bACTmb9BNXZJ/a2dA2ZfIdHRtxnhsdjBX9TGddpxspvC8RY3tdfyDxHlX6sHeSQKo32fRgIaue2R9VFloFA6ssVw/kA62UsQQqB8yZRzhtbP/+ppNg3peEIM5nPWYtwcE2myqrLSyhlg1CqQUd/z5nChM9fV7K6KyEBDK6Kx95t3LcOMO6NDhkbHFWyVommo5Tuot3btalo9gCxfbA5F5c1hqUiprw4JSz+6mDLW1Z4yxNbFQ2Lq1/5qLtfDBYqdeugo3V+2u5tZM1rzYAkRiVqYvN90ffXcV7y32FOw8aEmQc4+N1pr8MIIukGM="
      app: family-expense-tracker
      on: main