
jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd server-family-expense-tracker
    after_success:
      - npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "aJURtNxvt2FbAR09l46VqH/lGIKobu064j2h8MqHdOv23NIszVda696XzNzzVWWmZl1MbMwvjRUg0dpkc8RR4LdhhOdecD5BOjkf/77yE0CyCvRd4tWOv2FVwmXaUdAaN9h54+54BXtKikZxFiAtBPwQzGdCMPp/TUxsQG0m/6UtbHASBijl6M2XaZ51BzGOUVgegpjPn91fVcNVOdSK9yvFx7k6vkGU65pCc7XvEHfnOalxXboQcKUywcKvl2FjlU7qr1HnZkAJUeTPot/JKAvoLMgFkYpF4NFnHY5YPjoXpera7iZ3phnVogDJZEG7b6px6AfqtsLugJXzrMNuZZIXuYP9SFe7aOlLvCStfH6aWHKZ0SVDKpVjQXSW6NCfp3irlMDksfB6LVKyVSKIvbEEeNqFBRfUg5zSKGCVmaUUyKBvawbB8WBaK98RfCE20rT3CMcskL0zsFBf967xxps/NmP6EabE4MTZ3wH+VD7WFuBu9ITsp/pf0Qeokr+xB8Xi6tkkJLzlt8QnX7idVVDiz86Q5vO8zRL3VhC5IrZVy33e3T8GoMbqx2pqhrRhdH8MEj/nyT6jLDDPFe03TrkBfzAWJ1SThpy+PDronqDHXS2i2keHP+tzp4oEheruriP0zSaIKfnc/TTgrPajkWO7Mqa6560eBwyzLhifhwc="
      app: family-expense-tracker
      on: main