
jobs:
  include:

  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: Q7Ap/i4dfl6aQUge3Q5MIsnvIlY8Np2DuXcIb5byUrhScn3svs2il26Tgvo5tLysOZuFFo5wYsUhpA1jK6/el7LJh6pATly6yfM9xMYEmyVFZOWZLHozHn0IgWpwD4JTLnTKnKRUo7av9QHwcvmvWsdMs8EEX+P7iKgYtqgz7/rmxEFGdgskCB4DcZA8Fwl+SkL3+UXRr8OK1T6oas3/c5Xqmlgxvuirlw4efhM2McFNCayhdMemA0DFHF+aqp7hqsL9qOZS4sk7IhgGXA1qK0ngSHjuAObvYCUKXLwKAVSV5+5wby1MavWUp2kZYqnK41yy4NcuVelaCTURWHn/cguY3M2PcBUw7kiyYd3Y7gix+kwBVinsgp/UX2fIRcG7lxdujvZE83P3Ng8SOjmIXTjBdxWXDo2p0LyoVH5Vjbjm+VmCXGPRRc1gEyCHDZIcdyoH1jm2Zx1iDDF72+chV6+SJM+IQesvmQcNbW904BQP7g8LYd9AAyO/8dK8ZjqRqaN+MufADN+ImH9NGU1szcX76EHOwAba7K5WDklAhs8fJNUH3g8xqVTguhg6Aac1jF3nG7vniTCpTBJzOYgjeZQ7Ti/yydXS7W/J28cnE3OOcKdE9DE6wmPUs/NrPz2kK4Mwo5g2+fS6ZmR+Q5Vk7Srcwk0rLZcvE/NIjCcftYs=
      app: family-expense-tracker
      on: main