
jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd server-family-expense-tracker
    after_success:
      - npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "mZXibRORedrKGBpgPQdv1WZtA/duIz6PI+2nuNI6F0Gz7TkQOJNFLwuufOApZd3Boh4VxvVX7tRJ4ga6JC3sMgq9+w+PVPdYTv4+znJyb2L+L34y/waWCZhn7Xjznb7p7eYW/nitjGHIi9mtC2AtRKOSD5ETgfFkZQLa3dgclV+96n6N6pHlMowiikFNFPC8ZvKCICyMlMz0Wuu9+3HsiOm7cfm5oiXX7c8ywzcKUlrBfxmmlI5NZmm6LoK6ix48NQCDYGV3CI4zN9x/dL+tn2Ge/cjhdqYEJxBdNVIZZN3eY+fx6N/lHzvTPSrM5g9ulGrvRu3PCJ+IIqilJ4Bm4WiT44ixeuuDwtEocEWc74C7rBg0j7iIAVbcqZH/OCiaotkAiwFL65UBJlzJe/AzK9SVroN6JRDJCamFzElNcML5yGjjVwcyshGEQ5Sd8pu/wlhYR/TusFj4rPQ5Ysc2i/we2wtWmE0UCyM51d66yZnqHdadC6LvdTWnQpGQftwmsi3Mcww8vuCcVI2zqOWX6z9xFD1mZfu4Po3kGM6R9+bBwIFfF3cC9c/hwWhK+gHW9NYJnRQ6/5EnYsVMse5pWpZ9WMymcZVQbcvM44mPscv4lF8wsoqS3u8s3UxYISvF78ef2RgwsxL14bEeX1SLXSTW7GH3ydgrkufGs/YvYgc="
      app: family-expense-tracker
      on: main

# Környezeti beállítások:

  - language: node_js
    node_js:
      - "10"

    sudo: false

    cache:
      directories:
        - node_modules

    before_script:
      - npm install -g @angular/cli

    script:
      - ng lint
      - ng test --watch=false

    deploy:
      provider: heroku
      skip_cleanup: true
      keep-history: true
      api-key: 
        secure: "mZXibRORedrKGBpgPQdv1WZtA/duIz6PI+2nuNI6F0Gz7TkQOJNFLwuufOApZd3Boh4VxvVX7tRJ4ga6JC3sMgq9+w+PVPdYTv4+znJyb2L+L34y/waWCZhn7Xjznb7p7eYW/nitjGHIi9mtC2AtRKOSD5ETgfFkZQLa3dgclV+96n6N6pHlMowiikFNFPC8ZvKCICyMlMz0Wuu9+3HsiOm7cfm5oiXX7c8ywzcKUlrBfxmmlI5NZmm6LoK6ix48NQCDYGV3CI4zN9x/dL+tn2Ge/cjhdqYEJxBdNVIZZN3eY+fx6N/lHzvTPSrM5g9ulGrvRu3PCJ+IIqilJ4Bm4WiT44ixeuuDwtEocEWc74C7rBg0j7iIAVbcqZH/OCiaotkAiwFL65UBJlzJe/AzK9SVroN6JRDJCamFzElNcML5yGjjVwcyshGEQ5Sd8pu/wlhYR/TusFj4rPQ5Ysc2i/we2wtWmE0UCyM51d66yZnqHdadC6LvdTWnQpGQftwmsi3Mcww8vuCcVI2zqOWX6z9xFD1mZfu4Po3kGM6R9+bBwIFfF3cC9c/hwWhK+gHW9NYJnRQ6/5EnYsVMse5pWpZ9WMymcZVQbcvM44mPscv4lF8wsoqS3u8s3UxYISvF78ef2RgwsxL14bEeX1SLXSTW7GH3ydgrkufGs/YvYgc="
      app: expense-tracker--frontend
      on: main