jobs:
  include:

  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "nK7sHO36tjMkBHXn7EAfQCIosl0e5ha7veBtTWlC6MarHbD4fIv2NwuPGWCmf3BJx4ijhOfl+ypNOKB1q0o6uz+RXivsmeD0W8K6bY5RUFISCnctenC1Y5qLiyb4gq1rVmNEBGq92Q554NP9dfxfO9PL+bzrQYlz2b7Dpdv1lH8mHRe4XLdjtpvMgY5giBJxjA59rnpMn/EOsydVvpOr7XPxN8/TTfP0Ya41nL1FmCcONwXhtRMDcaBYcKMmAoUMp969POSFOOrlpETix09hLwCns7g2Bt0A9JBDLEhM88iJerJHHaBX92aO3B9+1zEdDn6p2fJbTxUk/mZwXBedJ9RIJERSvAguCerPRWWfacR8eZ10Yzbbd9BuWV6Qq7LuGH/4VPHl+YGwm0CJJ7T7FslITTWRQd2RGDtMEpQ95zB1NwQTUx6KCBHU/HIxCfl6flyrHZpG7okqw8VTZk27P1fo0B8Dll6x9DeEp3EN1m+oMMbCQRc2mFaLHsG8jl7ll7eZGUXUjs7ZX9vhYRONhnH5WEc2K/PomlhCCO7PGALzZUI6reHCnNRsw/DWDObScBJWYNGxMwywth7Xr2fXJ4T9vPeU8AAuva9bjP4sDXicsUc0hiqAA4SBE0HcHiIho29eq0ROesIfsN000tvNLG/cPfU6j28J3qnHv+91VrU="
      app: family-expense-tracker
      on: main