
jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd server-family-expense-tracker
    after_success:
      - npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "GEI71UVGTmnCq47P7ghev6NFWTyq7SfvPt/T+34yfLgybWjJbdEY8430P138WEk/oyouI7PSmShFQUSs1qPtm9yVp7mtqIlnCRH6AtL07FEDGIEsOPns31LlgKPlhuN+uFdd8aCQ9OkYDgrDmfMnn6BCjvlkc4fEoFB0FgekYYqO/g8veZoGoygiizelzVty3gJnruGuP9FDAJ7W08816jUKh+PYZHR3oj1T88ZKRydNHjiB6RwLVqCX9AN4nHsCA6Ol7yi6ld8EBuuYm1dvVdN8vhlRZlRlFu2FTd5ndIgLxcLwu3OGENQj8JdXZrBmKjVpcDsI6r8k5IPkXvZWCuKUvYGKwXgp/oOA2EuDWLYojWNZ0bqlelhwb062m/RD07NhlXETMe40+xZTPe0M0VHLArTI1Yw2VlSPB6wsfP0l63TmOpesHdCJXTFVL9fngmzXWJqCC7nonV0ofzeDRpk3CwrQyWSYfvQu9MYoTA7khgKUi2etHQn5exiHTXvU3PuepixyMznrKipsjsrSlCVlaQ6jws0ZrCnFDeZ37ZEXhsU0+MNSMzOhB8rqjWfRUZeujiMzP1IUCDhavEYQ+2ZD+a/RY04tywn5qal4fzmXD8iZpxNlsLoa2DDFlUHvA8QMRcF5E/802n2wT1toxj/nW3A+M3SMYSzvmjvZ5F0="
      app: family-expense-tracker
      on: main